### PR TITLE
Add VersionInfo to several tasks

### PR DESCRIPTION
**Pull request by kalantar**
Addresses issue https://github.com/iter8-tools/iter8/issues/939

Replace method WithRecommenedVersionForPromotion (and deprecated old version). The new version prefers to use  task.With.VersionInfo if defined. Otherwise it will (for now) use the versionInfo in the experiment.

Modified these task to add versionInfo as input (uses common definition provided in base)
 - common/bash
- common/promote-kubectl
- notification/http
- notification/github-workflow

### CODE REVIEW

**Comment by kalantar** [comment]
When versionInfo is simplified or removed from experiment, more changes will be needed. This PR is meant to be transitional allowing tutorials to be rewritten now.

**Review by sriumcp — CHANGES_REQUESTED** [review]
minor change requested

**Comment by sriumcp** [comment]
@kalantar Do you think it makes sense to repurpose this PR to fix this issue: https://github.com/iter8-tools/iter8/issues/945?

This would eliminate a chunk of code related to version recommended for promotion as well as interpolation (from etc3 and handlers respectively).

The implementation is simple -- 
1. `func (exp *Experiment) Winner() (map[string]interface{}, error)` would return the map of variables corresponding to winner if there is one, or error.
2. `func (exp *Experiment) WinnerOrBaseline() (map[string]interface{})` would return the map of variables corresponding to winner if there is one, or would return the map for the baseline (which always is present).

I don't believe anything else is needed for this to work.

**Review by sriumcp — APPROVED** [review]
lgtm

**Pull request merged**
