### PR TITLE
notification/http task

### PR DESCRIPTION
**Pull request by kalantar**
Implementation of https://github.com/iter8-tools/iter8/issues/845
See also documentation PR here: https://github.com/iter8-tools/iter8/pull/847

### CODE REVIEW

**Review by huang195 — APPROVED** [review]
/lgtm

**Review by sriumcp — CHANGES_REQUESTED** [review]
Please see comments on the issue.

**Comment by kalantar** [comment]
This PR has been updated to set a default body. The default is documented here: https://github.com/iter8-tools/iter8/pull/847. Note that this is slightly different from the proposal in the issue. Weights seemed a challenge. They are the latest observed weight not necessarily the current weight so perhaps best left out.

**Review by huang195 — DISMISSED** [review]
/lgtm

**Comment by kalantar** [comment]
Renamed and added weights (lastRecommendedWeights) as suggested.

**Review by sriumcp — APPROVED** [review]
lgtm

**Pull request merged**
