### PR TITLE
refactor so can avoid repeating common function

### PR DESCRIPTION
**Pull request by kalantar**
Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>
This refactors the location of experiment and the interpolation tags so that it is possible to write a common method to create the (default) tags for interpolation. Several tasks were duplicating this code. Without this refactor, import cycles are introduced.  See issue https://github.com/iter8-tools/iter8/issues/827

### CODE REVIEW

**Comment by huang195** [comment]
@kalantar I'm not familiar with this code, but reading the PR, it is doing what you described. However, from the PR itself and the linked issue, it's not clear to me what the "import cycles" you're referring to. Since you wrote some specific handlers in the past, you must have encountered it. It would be more clear if you could give an example.

**Comment by kalantar** [comment]
> So, I guess it's only some handler tasks could benefit from this refactor?
 @huang195 I encountered the same issue trying to write a `http-request` task as well. This work motivated the desire to refactor.

**Comment by kalantar** [comment]
@sriumcp @huang195 I hope the issue is clearer now about the problem. However, thanks to your questions, I have an idea that may make for a simpler refactor. This would be preferable. Let me try it before investing more time reviewing.  I'll switch to draft.

**Comment by kalantar** [comment]
Replaced by https://github.com/iter8-tools/handler/pull/38; closing

**Pull request closed without merging**
